In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
digits=load_digits()

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.3)


In [7]:
# creating logistic regression model 
lr=LogisticRegression(max_iter=1000)
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

c:\ProgramData\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9648148148148148

In [6]:
svm=SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9833333333333333

In [8]:
rf=RandomForestClassifier()
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9777777777777777

In [9]:
# we will use kfold becoz every time we execute the model the score is changed
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)  # there will be 3 splits
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [12]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [13]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [15]:
#  the above logsitic regression cloud also be made such way 
get_score(LogisticRegression(),X_train,X_test,y_train,y_test)

c:\ProgramData\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9592592592592593

In [19]:
# same way we could have done  for support vector classifier
get_score(SVC(),X_train,X_test,y_train,y_test)

0.9833333333333333

In [20]:
get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test)

# we are just making a  funtion to make model and calling it 
#  for each time with different classifier type to create 
#   different type of linear model


0.9777777777777777

In [21]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [22]:
#  now use kfold for digits selection 
from sklearn.model_selection import StratifiedKFold
folds =StratifiedKFold(n_splits=3)

In [23]:
scores_l=[]
scores_svm=[]
scores_rf=[]

for train_index,test_index in kf.split(digits.data):
    X_train,X_test,y_train,y_test=digits.data[train_index],digits.data[test_index],  \
                                   digits.target[train_index],digits.target[test_index]
    
                                   

In [24]:
get_score(LogisticRegression(),X_train,X_test,y_train,y_test)

c:\ProgramData\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9148580968280468

In [41]:
scores_l.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))
scores_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))
scores_rf.append(get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test))
# scores_rf.append(get_score(RandomForestClassifier(n_estimators=10),X_train,X_test,y_train,y_test))
# using n_estimators =10 will improve the score of RFC 

c:\ProgramData\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [32]:
scores_l

[0.9148580968280468, 0.9148580968280468, 0.9148580968280468]

In [42]:
scores_svm

[0.9549248747913188,
 0.9549248747913188,
 0.9549248747913188,
 0.9549248747913188]

In [40]:
scores_rf

[0.9265442404006677, 0.9365609348914858, 0.9181969949916527]

In [44]:
# the exact same thing we did up calculationg score of different 
#  model during different datasets within train test split  and k _fold
#  can be done very easily with the ready made method called
#   cross_val_score
from sklearn.model_selection import cross_val_score


In [45]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

c:\ProgramData\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\ProgramData\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [46]:
cross_val_score(SVC(),digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [47]:
cross_val_score(RandomForestClassifier(),digits.data, digits.target)

array([0.925     , 0.90833333, 0.9637883 , 0.96935933, 0.92479109])

In [48]:
cross_val_score(RandomForestClassifier(n_estimators=10),digits.data, digits.target)

array([0.91111111, 0.83611111, 0.92479109, 0.94150418, 0.88022284])

In [49]:
cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target)

array([0.93333333, 0.89722222, 0.94707521, 0.94428969, 0.92479109])

In [50]:
cross_val_score(RandomForestClassifier(n_estimators=50),digits.data, digits.target)

array([0.91666667, 0.92222222, 0.95821727, 0.97493036, 0.92479109])

In [ ]:
# we can see up adding parameter n_estimater more will increase the score each time